trigger:
  name: daily 0600 UTC
  identifier: scout_scrape_daily
  enabled: true
  orgIdentifier: default
  projectIdentifier: default_project
  pipelineIdentifier: scout_scrape
  source:
    type: Scheduled
    spec:
      type: Cron
      spec:
        expression: 0 6 * * *
  inputYaml: |
    pipeline:
      identifier: scout_scrape
      variables:
        - name: restore_from_release
          type: String
          value: "false"
      properties:
        ci:
          codebase:
            build:
              type: branch
              spec:
                branch: main
