# Base JP→EN card name map. Entries here are overridden by the cards table and card_mappings table at runtime in _build_jp_en_lookup.
JP_CARD_NAMES: dict[str, str] = {
    # --- Pokemon ---
    "イシズマイ": "Dwebble",
    "イベルタル": "Yveltal",
    "イワパレス": "Crustle",
    "イーブイ": "Eevee",
    "イーブイex": "Eevee ex",
    "エリカのクサイハナ": "Erika's Gloom",
    "エリカのナゾノクサ": "Erika's Oddish",
    "エリカのモンジャラ": "Erika's Tangela",
    "エリカのラフレシアex": "Erika's Vileplume ex",
    "エンペルトex": "Empoleon ex",
    "エーフィex": "Espeon ex",
    "オリーニョ": "Dolliv",
    "オリーヴァex": "Arboliva ex",
    "オーガポン いしずえのめんex": "Cornerstone Mask Ogerpon ex",
    "オーガポン いどのめんex": "Wellspring Mask Ogerpon ex",
    "オーガポン かまどのめんex": "Hearthflame Mask Ogerpon ex",
    "オーガポン みどりのめんex": "Teal Mask Ogerpon ex",
    "カプ・コケコex": "Tapu Koko ex",
    "ガチグマ アカツキex": "Bloodmoon Ursaluna ex",
    "キチキギス": "Fezandipiti",
    "キチキギスex": "Fezandipiti ex",
    "キュレム": "Kyurem",
    "ケーシィ": "Abra",
    "ゲノセクト": "Genesect",
    "ゲノセクトex": "Genesect ex",
    "コダック": "Psyduck",
    "コノヨザル": "Annihilape",
    "サマヨール": "Dusclops",
    "シェイミ": "Shaymin",
    "シャンデラ": "Chandelure",
    "シャリタツ": "Tatsugiri",
    "シロナのガバイト": "Cynthia's Gabite",
    "シロナのガブリアスex": "Cynthia's Garchomp ex",
    "シロナのフカマル": "Cynthia's Gible",
    "シロナのミカルゲ": "Cynthia's Spiritomb",
    "シロナのロズレイド": "Cynthia's Roserade",
    "シロナのロゼリア": "Cynthia's Roselia",
    "スピンロトム": "Fan Rotom",
    "スボミー": "Budew",
    "ソルロック": "Solrock",
    "ゾロアーク": "Zoroark",
    "タケルライコ": "Raging Bolt",
    "タケルライコex": "Raging Bolt ex",
    "ダイゴのダンバル": "Steven's Beldum",
    "ダイゴのメタグロスex": "Steven's Metagross ex",
    "ダイゴのメタング": "Steven's Metang",
    "チコリータ": "Chikorita",
    "テツノイサハex": "Iron Leaves ex",
    "テツノイワオ": "Iron Boulder",
    "テラパゴスex": "Terapagos ex",
    "ドラパルトex": "Dragapult ex",
    "ドラメシヤ": "Dreepy",
    "ドロンチ": "Drakloak",
    "ニャースex": "Meowth ex",
    "ノココッチ": "Dudunsparce",
    "ノコッチ": "Dunsparce",
    "ハリテヤマ": "Hariyama",
    "バチュル": "Joltik",
    "パオジアン": "Chien-Pao",
    "フーディン": "Alakazam",
    "ブースターex": "Flareon ex",
    "ベイリーフ": "Bayleef",
    "ホーホー": "Hoothoot",
    "ポッチャマ": "Piplup",
    "マクノシタ": "Makuhita",
    "マシマシラ": "Munkidori",
    "マリィのオーロンゲex": "Marnie's Grimmsnarl ex",
    "マリィのギモー": "Marnie's Morgrem",
    "マリィのベロバー": "Marnie's Impidimp",
    "ミニーブ": "Smoliv",
    "ムチュール": "Smoochum",
    "メガアブソルex": "Mega Absol ex",
    "メガエアームドex": "Mega Skarmory ex",
    "メガガルーラex": "Mega Kangaskhan ex",
    "メガジガルデex": "Mega Zygarde ex",
    "メガニウム": "Meganium",
    "メガヤドランex": "Mega Slowbro ex",
    "メガユキメノコex": "Mega Froslass ex",
    "メガルカリオex": "Mega Lucario ex",
    "ヤドキング": "Slowking",
    "ヤドン": "Slowpoke",
    "ユキメノコ": "Froslass",
    "ユキワラシ": "Snorunt",
    "ユンゲラー": "Kadabra",
    "ヨノワール": "Dusknoir",
    "ヨマワル": "Duskull",
    "ヨルノズク": "Noctowl",
    "ラティアスex": "Latias ex",
    "リオル": "Riolu",
    "リーフィアex": "Leafeon ex",
    "リーリエのピッピex": "Lillie's Clefairy ex",
    "ルナトーン": "Lunatone",
    "ロケット団のサンダー": "Team Rocket's Zapdos",
    "ロケット団のタマンチュラ": "Team Rocket's Tarountula",
    "ロケット団のドンカラス": "Team Rocket's Honchkrow",
    "ロケット団のフリーザー": "Team Rocket's Articuno",
    "ロケット団のポリゴン": "Team Rocket's Porygon",
    "ロケット団のポリゴン2": "Team Rocket's Porygon2",
    "ロケット団のミミッキュ": "Team Rocket's Mimikyu",
    "ロケット団のミュウツーex": "Team Rocket's Mewtwo ex",
    "ロケット団のヤミカラス": "Team Rocket's Murkrow",
    "ロケット団のワナイダー": "Team Rocket's Spidops",
    "ローブシン": "Conkeldurr",
    # --- Trainers ---
    "ネストボール": "Nest Ball",
    "ハイパーボール": "Ultra Ball",
    "なかよしポフィン": "Buddy-Buddy Poffin",
    "ボスの指令": "Boss's Orders",
    "ナンジャモ": "Iono",
    "博士の研究": "Professor's Research",
    "ふしぎなアメ": "Rare Candy",
    "夜のタンカ": "Night Stretcher",
    "すごいつりざお": "Super Rod",
    "大地の器": "Earthen Vessel",
    "カウンターキャッチャー": "Counter Catcher",
    "ポケモンいれかえ": "Switch",
    "あなぬけのヒモ": "Escape Rope",
    "エネルギー回収": "Energy Retrieval",
    "ジャッジマン": "Judge",
    "ペパー": "Pepper",
    "シロナの覇気": "Cynthia's Ambition",
    "ビワ": "Eri",
    "ツツジ": "Roxanne",
    "セイボリー": "Avery",
    "ともだちてちょう": "Pal Pad",
    "リーリエのおねがい": "Lillie's Determination",
    "Nの筋書き": "N's Scenario",
    "からておうの稽古": "Karate Chop Training",
    "きらめく結晶(ACE SPEC)": "Sparkling Crystal",
    "せいなるはい": "Sacred Ash",
    "ふうせん": "Air Balloon",
    "むしとりセット": "Bug Catching Set",
    "アオキの手際": "Aoki's Skill",
    "アカマツ": "Crispin",
    "アクロマの執念": "Colress's Tenacity",
    "アンフェアスタンプ(ACE SPEC)": "Unfair Stamp",
    "エキサイトスタジアム": "Excite Stadium",
    "エネルギーつけかえ": "Energy Switch",
    "エネルギーリサイクル": "Energy Recycler",
    "エネルギー転送": "Energy Search",
    "ガラスのラッパ": "Glass Trumpet",
    "クセロシキのたくらみ": "Xerosic's Scheme",
    "クラウン": "Crown",
    "グラビティーマウンテン": "Gravity Mountain",
    "サーファー": "Surfer",
    "シアノ": "Cyrano",
    "シークレットボックス(ACE SPEC)": "Secret Box",
    "ジャミングタワー": "Jamming Tower",
    "ジャンボアイス": "Jumbo Ice",
    "スイレンのお世話": "Lana's Care",
    "スグリ": "Kieran",
    "スパイクタウンジム": "Spikemuth Gym",
    "ゼイユ": "Carmine",
    "ゼロの大空洞": "Area Zero Underdepths",
    "タケシのスカウト": "Brock's Scout",
    "ツールスクラッパー": "Tool Scrapper",
    "テラスタルオーブ": "Tera Orb",
    "テレパス超エネルギー": "Telepathic Psychic Energy",
    "トウコ": "Hilda",
    "パワープロテイン": "Power Protein",
    "ヒカリ": "Dawn",
    "ヒーローマント(ACE SPEC)": "Hero's Cape",
    "ピュール": "Puelle",
    "ファイトゴング": "Fighting Gong",
    "ブライア": "Briar",
    "プレシャスキャリー(ACE SPEC)": "Precious Carry",
    "ポケギア3.0": "Pokegear 3.0",
    "ポケパッド": "Poke Pad",
    "ポケモン回収サイクロン(ACE SPEC)": "Scoop Up Cyclone",
    "マキシマムベルト(ACE SPEC)": "Maximum Belt",
    "マツバの確信": "Morty's Conviction",
    "ミストエネルギー": "Mist Energy",
    "ミツルの思いやり": "Wally's Compassion",
    "ミラクルインカム(ACE SPEC)": "Miracle Income",
    "メイのはげまし": "May's Encouragement",
    "ラッキーメット": "Lucky Helmet",
    "ロケット団のアテナ": "Team Rocket's Ariana",
    "ロケット団のアポロ": "Team Rocket's Archer",
    "ロケット団のサカキ": "Team Rocket's Giovanni",
    "ロケット団のファクトリー": "Team Rocket's Factory",
    "ロケット団のラムダ": "Team Rocket's Lambda",
    "ロケット団のランス": "Team Rocket's Lance",
    "ロケット団のレシーバー": "Team Rocket's Receiver",
    "ロケット団の監視塔": "Team Rocket's Watchtower",
    "ロケット団エネルギー": "Team Rocket Energy",
    "ロトりぼう": "Rotom Phone",
    "ワンダーパッチ": "Wonder Patch",
    "公民館": "Community Center",
    "危ない廃墟": "Dangerous Ruins",
    "夜のアカデミー": "Night Academy",
    "改造ハンマー": "Crushing Hammer",
    "暗号マニアの解読": "Cipher Admin's Decryption",
    "活力の森": "Vitality Forest",
    "鬼の仮面": "Ogre Mask",
    "ハイダイ": "Kofu",
    "リーリエの決心": "Lillie's Resolve",
    "シロナのパワーウエイト": "Cynthia's Power Weight",
    "バトルコロシアム": "Battle Colosseum",
    "プリズムエネルギー": "Prism Energy",
    "MBD": "MBD",
    # --- Energy ---
    "基本炎エネルギー": "Basic Fire Energy",
    "基本水エネルギー": "Basic Water Energy",
    "基本雷エネルギー": "Basic Lightning Energy",
    "基本超エネルギー": "Basic Psychic Energy",
    "基本闘エネルギー": "Basic Fighting Energy",
    "基本悪エネルギー": "Basic Darkness Energy",
    "基本鋼エネルギー": "Basic Metal Energy",
    "基本草エネルギー": "Basic Grass Energy",
    "基本無色エネルギー": "Basic Colorless Energy",
    "ダブルターボエネルギー": "Double Turbo Energy",
    "ジェットエネルギー": "Jet Energy",
    "ルミナスエネルギー": "Luminous Energy",
    "レガシーエネルギー": "Legacy Energy",
    "ネオアッパーエネルギー": "Neo Upper Energy",
    "イグニッションエネルギー": "Ignition Energy",
    "リッチエネルギー": "Enriching Energy",
    "ロック闘エネルギー": "Rocky Fighting Energy",
    "グロウ草エネルギー": "Growing Grass Energy",
    "ニトロ炎エネルギー": "Nitro Fire Energy",
    "バブル水エネルギー": "Bubble Water Energy",
    "マグネット鋼エネルギー": "Magnet Steel Energy",
    "ブーメランエネルギー": "Boomerang Energy",
    # --- Mega Pokemon ---
    "メガカイリューex": "Mega Dragonite ex",
    "メガクチートex": "Mega Mawile ex",
    "メガゲッコウガex": "Mega Greninja ex",
    "メガゲンガーex": "Mega Gengar ex",
    "メガサメハダーex": "Mega Sharpedo ex",
    "メガサーナイトex": "Mega Gardevoir ex",
    "メガスターミーex": "Mega Starmie ex",
    "メガタブンネex": "Mega Audino ex",
    "メガディアンシーex": "Mega Diancie ex",
    "メガドラミドロex": "Mega Dragalge ex",
    "メガピクシーex": "Mega Clefable ex",
    "メガフシギバナex": "Mega Venusaur ex",
    "メガフラエッテex": "Mega Floette ex",
    "メガヘラクロスex": "Mega Heracross ex",
    "メガミミロップex": "Mega Lopunny ex",
    "メガメガニウムex": "Mega Meganium ex",
    "メガヤンマex": "Mega Yanmega ex",
    "メガリザードンXex": "Mega Charizard X ex",
    # --- Pokemon (additional) ---
    "アズマオウ": "Seaking",
    "アチャモ": "Torchic",
    "アマルルガ": "Aurorus",
    "アラブルタケ": "Brute Bonnet",
    "アンジュフラエッテ": "Anzu Floette",
    "イイネイヌ": "Okidogi",
    "イベルタルex": "Yveltal ex",
    "イーユイ": "Chi-Yu",
    "ウガツホムラ": "Gouging Fire",
    "ウガツホムラex": "Gouging Fire ex",
    "ウネルミナモex": "Walking Wake ex",
    "エモンガ": "Emolga",
    "エレズン": "Toxel",
    "エースバーン": "Cinderace",
    "オニゴーリ": "Glalie",
    "オノノクス": "Haxorus",
    "カジッチュ": "Applin",
    "カミッチュ": "Dipplin",
    "カミツオロチex": "Hydrapple ex",
    "カメテテ": "Binacle",
    "カルボウ": "Charcadet",
    "カプ・ブルル": "Tapu Bulu",
    "ガチグマ アカツキ": "Bloodmoon Ursaluna",
    "ガメノデス": "Barbaracle",
    "キバニア": "Carvanha",
    "キリンリキ": "Girafarig",
    "キルリア": "Kirlia",
    "ギルガルド": "Aegislash",
    "クズモー": "Skrelp",
    "グレイシアex": "Glaceon ex",
    "ケロマツ": "Froakie",
    "ゲコガシラ": "Frogadier",
    "ゲッコウガex": "Greninja ex",
    "ゲンガー": "Gengar",
    "コクーン": "Kakuna",
    "コフキムシ": "Scatterbug",
    "コフーライ": "Spewpa",
    "コライドン": "Koraidon",
    "コライドンex": "Koraidon ex",
    "ゴリランダー": "Rillaboom",
    "ゴルバット": "Golbat",
    "ゴース": "Gastly",
    "ゴースト": "Haunter",
    "サケブシッポex": "Scream Tail ex",
    "サザンドラex": "Hydreigon ex",
    "サルノリ": "Grookey",
    "サンダー": "Zapdos",
    "サンダースex": "Jolteon ex",
    "ザルード": "Zarude",
    "シガロコ": "Rellor",
    "シュシュプ": "Spritzee",
    "ジヘッド": "Zweilous",
    "ジュナイパーex": "Decidueye ex",
    "ジュラルドン": "Duraludon",
    "ジーランス": "Relicanth",
    "ストリンダー": "Toxtricity",
    "スナノケガワ": "Sandy Shocks",
    "スピアーex": "Beedrill ex",
    "ズバット": "Zubat",
    "セレビィ": "Celebi",
    "ゼラオラ": "Zeraora",
    "ゼルネアス": "Xerneas",
    "ソウブレイズex": "Ceruledge ex",
    "ダンバル": "Beldum",
    "チュリネ": "Petilil",
    "チラチーノex": "Cinccino ex",
    "チラーミィ": "Minccino",
    "テツノカシラex": "Iron Crown ex",
    "ディアルガ": "Dialga",
    "ディンルー": "Ting-Lu",
    "デオキシス": "Deoxys",
    "デカグース": "Gumshoos",
    "デンチュラ": "Galvantula",
    "デンチュラex": "Galvantula ex",
    "トゲキッス": "Togekiss",
    "トゲチック": "Togetic",
    "トゲピー": "Togepi",
    "トサキント": "Goldeen",
    "ドレディア": "Lilligant",
    "ドータクン": "Bronzong",
    "ドーミラー": "Bronzor",
    "ナゲツケサル": "Passimian",
    "ナックラー": "Trapinch",
    "ニダンギル": "Doublade",
    "ニンフィア": "Sylveon",
    "ニンフィアex": "Sylveon ex",
    "ノココッチex": "Dudunsparce ex",
    "ハクリュー": "Dragonair",
    "ハバタクカミ": "Flutter Mane",
    "バケッチャ": "Pumpkaboo",
    "バシャーモ": "Blaziken",
    "バシャーモex": "Blaziken ex",
    "バチンキー": "Thwackey",
    "バッフロン": "Bouffalant",
    "パルデア ケンタロス": "Paldean Tauros",
    "パンプジンex": "Gourgeist ex",
    "ヒトモシ": "Litwick",
    "ヒトカゲ": "Charmander",
    "ヒトツキ": "Honedge",
    "ヒトデマン": "Staryu",
    "ヒバニー": "Scorbunny",
    "ヒンバス": "Feebas",
    "ヒードラン": "Heatran",
    "ビクティニ": "Victini",
    "ビビヨン": "Vivillon",
    "ビブラーバ": "Vibrava",
    "ビードル": "Weedle",
    "ピカチュウex": "Pikachu ex",
    "ピクシー": "Clefable",
    "ピッピ": "Clefairy",
    "ファイヤー": "Moltres",
    "フクスロー": "Dartrix",
    "フシギソウ": "Ivysaur",
    "フシギダネ": "Bulbasaur",
    "フライゴンex": "Flygon ex",
    "フレフワン": "Aromatisse",
    "ブラックキュレムex": "Black Kyurem ex",
    "ブリジュラス": "Archaludon",
    "ブリジュラスex": "Archaludon ex",
    "ブルンゲルex": "Jellicent ex",
    "プルリル": "Frillish",
    "ベラカス": "Rabsca",
    "ホウオウ": "Ho-Oh",
    "ホルビー": "Bunnelby",
    "ホルード": "Diggersby",
    "ママンボウ": "Alomomola",
    "マラカッチ": "Maractus",
    "ミニリュウ": "Dratini",
    "ミネズミ": "Patrat",
    "ミミロル": "Buneary",
    "ミロカロスex": "Milotic ex",
    "メタグロス": "Metagross",
    "メタング": "Metang",
    "メレシー": "Carbink",
    "モクロー": "Rowlet",
    "モグリュー": "Drilbur",
    "モノズ": "Deino",
    "モモワロウ": "Pecharunt",
    "モモワロウex": "Pecharunt ex",
    "ヤングース": "Yungoos",
    "ヤンヤンマ": "Yanma",
    "ユクシー": "Uxie",
    "ランプラー": "Lampent",
    "ラブトロス": "Enamorus",
    "ラルトス": "Ralts",
    "リキキリンex": "Farigiraf ex",
    "リーリエのしんじゅ": "Lillie's Pearl",
    "ルチャブル": "Hawlucha",
    "レイスポス": "Spectrier",
    "レシラムex": "Reshiram ex",
    "レジギガス": "Regigigas",
    "ワカシャモ": "Combusken",
    "ワニノコ": "Totodile",
    # --- Character Pokemon ---
    "Nのシンボラー": "N's Sigilyph",
    "Nのゼクロム": "N's Zekrom",
    "Nのゾロア": "N's Zorua",
    "Nのゾロアークex": "N's Zoroark ex",
    "Nのダルマッカ": "N's Darumaka",
    "Nのヒヒダルマ": "N's Darmanitan",
    "Nのレシラム": "N's Reshiram",
    "ナンジャモのカイデン": "Iono's Wattrel",
    "ナンジャモのズピカ": "Iono's Bellibolt",
    "ナンジャモのタイカイデン": "Iono's Kilowattrel",
    "ナンジャモのハラバリーex": "Iono's Bellibolt ex",
    "ナンジャモのビリリダマ": "Iono's Voltorb",
    "カスミのギャラドス": "Misty's Gyarados",
    "カスミのコイキング": "Misty's Magikarp",
    "カスミのコダック": "Misty's Psyduck",
    "カスミのスターミー": "Misty's Starmie",
    "カスミのヒトデマン": "Misty's Staryu",
    "ホップのウッウ": "Hop's Cramorant",
    "ホップのウールー": "Hop's Wooloo",
    "ホップのオーロット": "Hop's Trevenant",
    "ホップのカビゴン": "Hop's Snorlax",
    "ホップのザシアンex": "Hop's Zacian ex",
    "ホップのバイウールー": "Hop's Dubwool",
    "ホップのボクレー": "Hop's Phantump",
    "ヒビキのウソッキー": "Ethan's Sudowoodo",
    "ヒビキのバクフーン": "Ethan's Typhlosion",
    "ヒビキのヒノアラシ": "Ethan's Cyndaquil",
    "ヒビキのピチュー": "Ethan's Pichu",
    "ヒビキのマグマラシ": "Ethan's Quilava",
    "マリィのモルペコ": "Marnie's Morpeko",
    "ロケット団のガルーラex": "Team Rocket's Kangaskhan ex",
    "ロケット団のクロバットex": "Team Rocket's Crobat ex",
    "ロケット団のゴルバット": "Team Rocket's Golbat",
    "ロケット団のズバット": "Team Rocket's Zubat",
    "ロケット団のソーナンス": "Team Rocket's Wobbuffet",
    "ロケット団のニューラ": "Team Rocket's Sneasel",
    "ロケット団のポリゴンZ": "Team Rocket's Porygon-Z",
    # --- Character Trainers ---
    "アセロラのいたずら": "Acerola's Prank",
    "AZの安らぎ": "AZ's Serenity",
    "Nの城": "N's Castle",
    "Nのポイントアップ": "N's Power Up",
    "アイリスの闘志": "Iris's Fighting Spirit",
    "アンズの秘技": "Janine's Secret Art",
    "カキツバタ": "Kakitsubata",
    "カシオペア": "Cassiopeia",
    "カナリィ": "Canary",
    "ギーマの一手": "Grimsley's Move",
    "ゴヨウ": "Lucian",
    "サザレ": "Sazare",
    "ジプソ": "Gypso",
    "セイジ": "Sage",
    "タラゴン": "Tarragon",
    "タロ": "Talo",
    "ハッサク": "Hassel",
    "ヒビキの冒険": "Ethan's Adventure",
    "ビリオとネア": "Bilio and Nea",
    "ホップのバッグ": "Hop's Bag",
    "ホップのこだわりハチマキ": "Hop's Choice Band",
    "ホミカの演奏": "Roxie's Performance",
    "マコモ": "Fennel",
    "マチスの取引": "Lt. Surge's Deal",
    "ユカリ": "Yukari",
    "ルチアのアピール": "Lucia's Appeal",
    "ロケット団のスーパーボール": "Team Rocket's Great Ball",
    "ロケット団のびっくりボム": "Team Rocket's Surprise Bomb",
    # --- Trainers (additional) ---
    "あやしい時計": "Suspicious Clock",
    "いいきずぐすり": "Potion",
    "おとりよせボックス": "Order Box",
    "おはやし笛": "Festival Flute",
    "お祭り会場": "Festival Grounds",
    "くさりもち": "Leftovers",
    "つりざおMAX(ACE SPEC)": "Super Rod MAX",
    "でんきだま": "Light Ball",
    "とりかえチケット": "Switch Ticket",
    "なみのりビーチ": "Surfing Beach",
    "ぼうがいレター": "Interference Letter",
    "むしよけスプレー": "Repel",
    "エネはたき": "Energy Removal",
    "カウンターゲイン": "Counter Gain",
    "クラッシュハンマー": "Crushing Hammer",
    "コアメモリ": "Core Memory",
    "コック": "Chef",
    "サバイブギプス(ACE SPEC)": "Survival Cast",
    "スペシャルレッドカード": "Special Red Card",
    "ダークボール": "Dusk Ball",
    "デラックスボム(ACE SPEC)": "Deluxe Bomb",
    "ニュートラルセンター(ACE SPEC)": "Neutral Center",
    "ハイパーアロマ(ACE SPEC)": "Hyper Aroma",
    "ハッコウシティ": "Levincia",
    "ウタンのみ": "Payapa Berry",
    "ハバンのみ": "Haban Berry",
    "ハロンタウン": "Haron Town",
    "ハンディサーキュレーター": "Handy Circulator",
    "ハンドトリマー": "Hand Trimmer",
    "パンクメット": "Punk Helmet",
    "パーフェクトミキサー(ACE SPEC)": "Perfect Mixer",
    "ヒートバーナー": "Heat Burner",
    "フルメタルラボ": "Full Metal Lab",
    "ブレイブバングル": "Brave Bangle",
    "プライムキャッチャー(ACE SPEC)": "Prime Catcher",
    "プリズムタワー": "Prism Tower",
    "ポケモンキャッチャー": "Pokemon Catcher",
    "メガシグナル": "Mega Signal",
    "ミアレシティ": "Lumiose City",
    "ミステリーガーデン": "Mystery Garden",
    "偉大な大樹(ACE SPEC)": "Great Tree",
    "力の砂時計": "Power Hourglass",
    "危険な密林": "Dangerous Jungle",
    "夜の鉱山": "Night Mine",
    "大漁ネット": "Fishing Net",
    "探検家の先導": "Explorer's Guide",
    "推理セット": "Detective Set",
    "緊急ボード": "Emergency Board",
    "重力玉": "Gravity Ball",
    # --- Missing translations (low-frequency) ---
    "Nのバイバニラ": "N's Vanilluxe",
    "アバゴーラ": "Carracosta",
    "イイネイヌex": "Okidogi ex",
    "ウエートレス": "Waitress",
    "オーダイル": "Feraligatr",
    "きずぐすり": "Potion",
    "ぶあついうろこ": "Thick Scales",
    "スクランブルスイッチ(ACE SPEC)": "Scramble Switch",
    "デリバード": "Delibird",
    "フォッコ": "Fennekin",
    "プロトーガ": "Tirtouga",
    "マフォクシー": "Delphox",
    "マリル": "Marill",
    "マリルリ": "Azumarill",
    "メガラティアスex": "Mega Latias ex",
    "ミライドンex": "Miraidon ex",
    "モルペコ": "Morpeko",
    "リグレー": "Elgyem",
    "古びたふたの化石": "Old Dome Fossil",
    # --- Accent normalization (Limitless uses accented, we normalize to ASCII) ---
    "Poké Pad": "Poke Pad",
    "Pokégear 3.0": "Pokegear 3.0",
    "Pokémon Catcher": "Pokemon Catcher",
}
